### ISSUE TITLE
Error type

### ISSUE THREAD

**Issue by JuanYyo** [lczub/TestLink-API-Python-client#125]
I have just set TESTLINK_API_PYTHON_SERVER_URL and TESTLINK_API_PYTHON_DEVKEY and execute the following in python:

>>> tls = testlink.TestlinkAPIClient(TESTLINK_API_PYTHON_SERVER_URL,TESTLINK_API_PYTHON_DEVKEY)

>>> tls.about()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qa/.pyenv/versions/3.6.0/lib/python3.6/site-packages/testlink/testlinkdecorators.py", line 78, in wrapperWithoutArgs
    return self.callServerWithPosArgs(methodAPI.__name__)
  File "/home/qa/.pyenv/versions/3.6.0/lib/python3.6/site-packages/testlink/testlinkapigeneric.py", line 1582, in callServerWithPosArgs
    response = self._callServer(methodNameAPI, argsOptional)
  File "/home/qa/.pyenv/versions/3.6.0/lib/python3.6/site-packages/testlink/testlinkapigeneric.py", line 2061, in _callServer
    raise testlinkerrors.TLConnectionError(new_msg)
testlink.testlinkerrors.TLConnectionError: problems connecting the TestLink Server http://localhost/testlink/lib/api/xmlrpc/v1/xmlrpc.php
[Errno 111] Connection refused

**Comment by lczub** [comment]
no further response
