### ISSUE TITLE
KeyError thrown in getProjectIDByNode

### ISSUE THREAD

**Issue by elapfra** [lczub/TestLink-API-Python-client#149]
Hi,

Thanks for this library, it works great.

However, I encounter this error while running "TestLinkExample.py"

```
Traceback (most recent call last):
  File "/home/elapfra/code/TestLink-API-Python-client/example/TestLinkExample.py", line 713, in <module>
    response = myTestLink.copyTCnewVersion(newTestCaseID_B, 
  File "/home/elapfra/code/TestLink-API-Python-client/src/testlink/testlinkapi.py", line 188, in copyTCnewVersion
    return self._copyTC(origTestCaseId, changedAttributes, origVersion, 
  File "/home/elapfra/code/TestLink-API-Python-client/src/testlink/testlinkapi.py", line 258, in _copyTC
    origArgItems['testprojectid'] = self.getProjectIDByNode(origTestCaseId)
  File "/home/elapfra/code/TestLink-API-Python-client/src/testlink/testlinkapi.py", line 166, in getProjectIDByNode
    node_path = self.getFullPath(int(a_nodeid))[a_nodeid]
KeyError: 563
```

It seems to me the dict should be accessed by string.
This works.
    node_path = self.getFullPath(int(a_nodeid))[**str(a_nodeid)**]

**Comment by lczub** [comment]
Hello Elapfra,
thanks for your response.
It is interesting, cause before I published the releases the examples were working .
So maybe it is an issue driven by special version combinations.

Could you tell me the versions from your current used
* python
* testlink server
* TestLink-API-Python-client

That might help to understand what happens.

Regards Luiko
