### ISSUE TITLE
getting "problems connecting the TestLink Server" at specific time

### ISSUE THREAD

**Issue by usmanmukhtar** [lczub/TestLink-API-Python-client#161]
Hi,

I've been getting this error for a specific period of time. at times it works and I don't change anything and all of a sudden it gives me this error.

**Traceback**

`TLConnectionError('problems connecting the TestLink Server http://testlink.fomarkmedia.com/lib/api/xmlrpc/v1/xmlrpc.php\n<ProtocolError for testlink.fomarkmedia.com/lib/api/xmlrpc/v1/xmlrpc.php: 409 Conflict>')
Traceback (most recent call last):
  File "/Users/macbook/Desktop/BitBucket/BaseAutomationProject/src/server/server/testlink/testlinkapigeneric.py", line 2057, in _callServer
    response = getattr(self.server.tl, methodNameAPI)(argsAPI)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1183, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for testlink.fomarkmedia.com/lib/api/xmlrpc/v1/xmlrpc.php: 409 Conflict>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/Desktop/BitBucket/BaseAutomationProject/venv/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/macbook/Desktop/BitBucket/BaseAutomationProject/venv/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/macbook/Desktop/BitBucket/BaseAutomationProject/src/server/page_app/task.py", line 26, in execute_test_plan
    project = tl_helper.getTestProjectByName(request_data.get("project"))
  File "/Users/macbook/Desktop/BitBucket/BaseAutomationProject/src/server/server/testlink/testlinkdecorators.py", line 112, in wrapperAddDevKey
    return methodAPI(self, *argsPositional, **argsOptional)
  File "/Users/macbook/Desktop/BitBucket/BaseAutomationProject/src/server/server/testlink/testlinkdecorators.py", line 99, in wrapperWithArgs
    return self.callServerWithPosArgs(methodAPI.__name__,
  File "/Users/macbook/Desktop/BitBucket/BaseAutomationProject/src/server/server/testlink/testlinkapigeneric.py", line 1582, in callServerWithPosArgs
    response = self._callServer(methodNameAPI, argsOptional)
  File "/Users/macbook/Desktop/BitBucket/BaseAutomationProject/src/server/server/testlink/testlinkapigeneric.py", line 2061, in _callServer
    raise testlinkerrors.TLConnectionError(new_msg)
server.testlink.testlinkerrors.TLConnectionError: problems connecting the TestLink Server http://testlink.fomarkmedia.com/lib/api/xmlrpc/v1/xmlrpc.php
<ProtocolError for testlink.fomarkmedia.com/lib/api/xmlrpc/v1/xmlrpc.php: 409 Conflict>`

**Comment by lczub** [comment]
Hello Usman,

looks as if inside the testlink server itself happen something unexpected - maybe tl py api call a method not yet supported by your tl server?
* which TL server version and which tl api py release are you suing?
* could you see inside your tl server logs events / errors / warnings, where timestamp matches to observed 409 conflict issues?

Regards Luiko

**Comment by lczub** [comment]
Hello Usman,

Which API py release matches to which TL server version is documented in [CHANGES.rst](https://github.com/lczub/TestLink-API-Python-client/blob/master/CHANGES.rst)

You find there TL 1.18 not listed, cause it was , when I remember correct, very fast replaced by a not well running 1.19 and afterwards with 1.20, which current is maintained on [testlink_1_9_20_fixed](https://github.com/TestLinkOpenSourceTRMS/testlink-code/tree/testlink_1_9_20_fixed).

You find your current used API py release in [src/testlink/version.py](https://github.com/lczub/TestLink-API-Python-client/blob/master/src/testlink/version.py)

Regards Luiko
