### ISSUE TITLE
countTestCasesTS should handle the sufficient right errors

### ISSUE THREAD

**Issue by lczub** [lczub/TestLink-API-Python-client#62]
extended travis config, which runs TestLinkExample against TL Demo, aborts with an error (see [build job 45.4](https://travis-ci.org/lczub/TestLink-API-Python-client/jobs/83477873) ).
Reason seams to be, that the used test account _pyTLapi_ has  not the right, to get info of all test cases from all test projects.

countTestCasesTS should handle the sufficient right errors

```
Number of TestPlans                : 249 
Number of TestSuites               : 99 
Traceback (most recent call last):
  File "example/TestLinkExample.py", line 688, in <module>
    print("Number of TestCases (in TestSuites): %s " % myTestLink.countTestCasesTS())
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/testlink/testlinkapi.py", line 416, in countTestCasesTS
    TestSuite['id'],'true','full')
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/testlink/testlinkdecorators.py", line 140, in wrapperReplaceTLResponseError
...
testlink.testlinkerrors.TLResponseError: 2010: User corresponding to Developer Key has insufficient rights to perform this action- Details: right mgt_view_tc, test project id: 5922, test plan id: 
getTestCasesForTestSuite({'details': 'full', 'testsuiteid': '5941', 'devKey': '3ec96581bb3d8a34cd28ce338b641063', 'deep': 'true'})
The command "if [[ $TESTLINK_API_PYTHON_SERVER_URL && $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python example/TestLinkExample.py; fi" exited with 1.
```

**Comment by lczub** [comment]
currently no further action planned, cause online TL demo applicatio is down over one year and these test are not runable
